# Generated by Django 3.1.5 on 2021-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210119_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Название пункта'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=300, verbose_name='Ссылка'),
        ),
    ]
