# Generated by Django 3.1.5 on 2021-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210120_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_named_url',
            field=models.BooleanField(default=False, verbose_name='Named url?'),
        ),
    ]
